### ISSUE TITLE
ერთ-ერთი ლინკი არ მუშაობს

### ISSUE THREAD

**Issue by getsadzeg** [mirianashvili/medium-georgian-stories#1]
[როგორ იგეგმება UX — დიზაინის პროცესი](https://medium.com/@soseba/%E1%83%A0%E1%83%9D%E1%83%92%E1%83%9D%E1%83%A0-%E1%83%98%E1%83%92%E1%83%94%E1%83%92%E1%83%9B%E1%83%94%E1%83%91%E1%83%90-ux-%E1%83%93%E1%83%98%E1%83%96%E1%83%90%E1%83%98%E1%83%9C%E1%83%98%E1%83%A1-%E1%83%9E%E1%83%A0%E1%83%9D%E1%83%AA%E1%83%94%E1%83%A1%E1%83%98-82d5d083d24e) ლინკი არ მუშაობს. წაშლილი აქვს ავტორს.

**Comment by sandromirr** [comment]
@getsadzeg წავშალე ეგ ლინკი.
